[package]
name = "querysense"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs" 

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["macros"] }
config = "0.14.0"
dotenvy = "0.15.7"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.5.0"
serde_json = "1.0"
tokio = { version = "1.40.0", features = ["full", "rt"] }
tower = "0.5.0"
tower-http = { version = "0.5.2", features = ["cors", "fs", "trace"] }
tower-request-id = "0.3.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
chrono = { version = "0.4.38", features = ["serde"] }
lazy_static = "1.5.0"
notify = "6.1.1"
http = "1.1.0"
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
csv = "1.3.0"
sqlite-vec = "0.1.3"
rusqlite = { version = "0.32.0", features = ["bundled"] }
zerocopy = "0.8.5"
clap = { version = "4.5.20", features = ["derive"] }
ammonia = "4.0.0"
camino = "1.1.9"
