[package]
name = "querysense-common"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
axum.workspace = true
serde.workspace = true
# serde-aux.workspace = true
serde_json.workspace = true
tracing.workspace = true


