[package]
name = "querysense-openai"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
reqwest.workspace = true
tokio.workspace = true
eyre.workspace = true

